[package]
name = "cli-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
termion = "3"
anyhow = "1"
lame = "0.1.3"
